#!/usr/bin/env bash
# duplicate web-01 to web-02

sudo apt-get update
sudo apt-get install -y nginx 

# allowing nginx on firewall
sudo apt-get install ufw
sudo ufw allow 'Nginx HTTP'

# creating new index
echo "Holberton School" > /var/www/html/index.html

# create new error page
echo "Ceci n'est pas une page" > /var/www/html/error_404.html

# default server config file

cat <<EOF > /etc/nginx/sites-enabled/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html
    server_name_;
    add_header X-Served-By \$hostname;
    location / {
      try_files \$uri \$uri/ =404;
    }
    if (\$request_filename ~ redirect_me){
      rewrite ^ https://th3-gr00t.tk/ permanent;
    }
    error_page 404 /error_404.html;
    location = /error_404.html {
      internal;
    }
}
EOF

# Restarting nginx
sudo service nginx restart
